workflow:
  rules:
    - if: $CI_COMMIT_TAG

image: docker:stable

variables:
  DOCKER_TLS_CERTDIR: "/certs"

services:
  - docker:dind

before_script:
  - docker info

build:
  stage: build
  script:
    - docker build -t rodesp7/www .
    - docker tag rodesp7/www rodesp7/www:$CI_COMMIT_TAG
    - echo "$DockerHub_AccessToken" | docker login -u rodesp7 --password-stdin
    - docker push rodesp7/www:$CI_COMMIT_TAG
  artifacts:
    expire_in: 1 day

after_script:
  - rm /root/.docker/config.json