workflow:
  rules:
    - if: $CI_COMMIT_TAG

image: docker:stable

variables:
  DOCKER_TLS_CERTDIR: "/certs"

services:
  - docker:dind

before_script:
  - docker info

build:
  stage: build
  script:
    - docker build -t rodesp/www .
    - docker tag rodesp/www us.gcr.io/rodesp-kubernetes-cluster/rodesp/www:$CI_COMMIT_TAG
    - echo "$GCP_SERVICE_ACCOUNT" | base64 -d | docker login -u _json_key --password-stdin https://us.gcr.io
    - docker push us.gcr.io/rodesp-kubernetes-cluster/rodesp/www:$CI_COMMIT_TAG
  artifacts:
    expire_in: 1 day

after_script:
  - rm /root/.docker/config.json