workflow:
  rules:
    - if: $CI_COMMIT_TAG

image: docker:latest

variables:
  MOUNT_POINT: /builds/#CI_PROJECT_PATH/mnt

services:
  - docker:dind

build-image:
  stage: build
  script:
    - mkdir -p "$MOUNT_POINT"
    - docker build -t rodesp/www .
  artifacts:
    expire_in: 1 day

deploy_production:
  stage: deploy
  environment: { name: 'Production' }
  script:
  - docker tag rodesp/www us.gcr.io/rodesp-kubernetes-cluster/rodesp/www:$CI_COMMIT_TAG
  - docker push us.gcr.io/rodesp-kubernetes-cluster/rodesp/www:$CI_COMMIT_TAG

after_script:
- rm /tmp/$CI_PIPELINE_ID.json