workflow:
  rules:
    - if: $CI_COMMIT_TAG

image: docker:latest

services:
  - docker:dind

build-push-image:
  stage: build
  script:
    - docker build -t rodesp/www .
    - docker tag rodesp/www us.gcr.io/rodesp-kubernetes-cluster/rodesp/www:$CI_COMMIT_TAG
    - docker push us.gcr.io/rodesp-kubernetes-cluster/rodesp/www:$CI_COMMIT_TAG
  artifacts:
    expire_in: 1 day
