workflow:
  rules:
    - if: $CI_COMMIT_TAG

image: docker:latest

services:
  - docker:dind

variables:
  MOUNT_POINT: /builds/$CI_PROJECT_PATH/mnt

build-image:
  image: node:12
  stage: build
  script:
    - docker build -t rodesp/www .
  artifacts:
    expire_in: 1 day

deploy_production:
  stage: deploy
  environment: { name: 'Production' }
  only:
  - master
  script:
  - docker tag rodesp/www us.gcr.io/rodesp-kubernetes-cluster/rodesp/www:$CI_COMMIT_TAG
  - docker push us.gcr.io/rodesp-kubernetes-cluster/rodesp/www:$CI_COMMIT_TAG

after_script:
- rm /tmp/$CI_PIPELINE_ID.json