workflow:
  rules:
    - if: $CI_COMMIT_TAG

before_script:
  - echo "$GCP_SERVICE_ACCOUNT" | base64 -d >> "$HOME/kf.json"

image: docker:latest

build-push-image:
  stage: build
  script:
    - docker build -t rodesp/www .
    - docker tag rodesp/www us.gcr.io/rodesp-kubernetes-cluster/rodesp/www:$CI_COMMIT_TAG
    - docker login -u _json_key --password-stdin https://us.gcr.io < $HOME/kf.json
    - docker push us.gcr.io/rodesp-kubernetes-cluster/rodesp/www:$CI_COMMIT_TAG
  artifacts:
    expire_in: 1 day
