name: Lint Code

on:
  workflow_dispatch:
  push:

jobs:
  build_image:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install Deps
        run: npm install
      - name: Lint
        run: npm lint
